### ISSUE TITLE
error with newer opencv with cv2.findContours

### ISSUE THREAD

**Issue by miguelgfierro** [miguelgfierro/pybase#3]
```
_____________________________________ [doctest] pybase.image_base.opencv_features.largest_contour ______________________________________
006
007     Args:
008         mask (np.array): Binary image.
009
010     Returns:
011         np.array: Array of points.
012
013     Examples:
014         >>> mask = cv2.imread('share/Lenna_mask.png', 0)
015         >>> cnts = largest_contour(mask)
UNEXPECTED EXCEPTION: ValueError('not enough values to unpack (expected 3, got 2)',)
Traceback (most recent call last):

  File "/home/miguel/anaconda/envs/codebase/lib/python3.6/doctest.py", line 1330, in __run
    compileflags, 1), test.globs)

  File "<doctest pybase.image_base.opencv_features.largest_contour[1]>", line 1, in <module>

  File "/home/miguel/repos/pybase/image_base/opencv_features.py", line 19, in largest_contour
    _, contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

ValueError: not enough values to unpack (expected 3, got 2)

```

**Comment by miguelgfierro** [comment]
fixed with #45
